### ISSUE TITLE
error with React v15

### ISSUE THREAD

**Issue by mingfang** [milankinen/react-combinators#9]
rx.all.js:77 Uncaught TypeError: (0 , _reactLibReactElement.cloneAndReplaceProps) is not a functionassignObservableValues @ combineVDOM.js:68_loop2 @ combineVDOM.js:54_loop @ combineVDOM.js:49assignObservableValues @ combineVDOM.js:43(anonymous function) @

**Comment by brn** [comment]
@mingfang 
Pull request #10 had been sent.

**Comment by milankinen** [comment]
Thanks! I'll check that tonight

**Comment by milankinen** [comment]
Sorry took a bit longer but released now in `0.4.0`. Thanks!
